name: Lint - [Frontend]

# Triggers the workflow on push and pull requests
on:
  pull_request:
  
jobs:
  run-linters:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Install yarn dependencies and Run ESLint
      run: |
        cd client
        yarn install
        yarn run lint