name: Format Code

# Triggers the workflow on push
on:
  push:
    branches:
    - dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        commit_message: same_commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Install yarn dependencies and Run ESLint
      run: |
        cd client
        yarn install
        yarn run lint --fix
        git config --global user.name 'Eniola Osabiya'
        git config --global user.email 'eni4sure@users.noreply.github.com'
        git commit -am "EsLint"
        git push